# -*- coding: utf-8 -*-
"""Chapter 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1OxjylJ-DLdO1FPzZAKe7AA1tLYG6t3

# print function
"""

print("hello world")        # print is a function (more later)

"""# Example: Using the math module ( built in module )"""

import math
print(math.sqrt(16))  # Output: 4.0
print(math.pi)        # Output: 3.141592653589793

"""# Example: Using the random module


"""

import random
print(random.randint(1, 10))  # Output: Random number between 1 and 10

def greet(name):
    return f"Hello, {name}!"

greet("Ayush Kumar Singh")

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

"""# USING PYTHON AS A CALCULATOR
We can use python as a calculator by typing “python” ↵ on the terminal.
This opens REPL or Read Evaluate Print Loop.

# Comments
"""

# This is a Single-Line Comment

"""This is an amazing
example of a Multiline
comment!"""

'''This is an amazing
example of a Multiline
comment! '''

"""# Dynamic Typing"""

x = 10           # x is an integer
x = "Batman"     # now x is a string
x = 3.14         # now x is a float

print(x)

"""# Multiple Assignment"""

# Eg :
a, b, c = 1, 2, 3
print(a)  # 1
print(b)  # 2
print(c)  # 3

"""# del Statement"""

x = 100
del x
# print(x) #→ ❌ Error: x is not defined

nums = [10, 20, 30, 40]
del nums[2]
print(nums)  # [10, 20, 40]

nums = [10, 20, 30, 40]
del nums[1:]   # deletes from index 1 to end
print(nums)    # [10]

person = {"name": "Batman", "age": 30}
del person["age"]
print(person)  # {'name': 'Batman'}

"""# In operator

"""

# With strings
print('a' in 'Batman')        # True
print('z' in 'Batman')        # False

# With lists
nums = [1, 2, 3]
print(2 in nums)              # True
print(5 in nums)              # False

"""# Chaining Operator"""

x = 10
print(5 < x < 20)     # True → checks if x > 5 AND x < 20
print(1 == x < 100)   # False → 1 == x is False, so result is False